function renderReport(){
const p=currentProject(); if(!p){document.getElementById('view-report').innerHTML='<div class="empty">Создайте проект</div>';return;} const best=bestServices(p), risks=calcRisks(p), qs=questionsForClient(p), kpi=kpiMath(p);
const summaryHtml=textToParagraphs(analysisStrategyText(p));
const audienceHtml=`<p>${esc(p.portrait||'Портрет ЦА нужно уточнить. В коммуникации важно закрывать страхи: цена, сроки, качество, гарантия, надежность подрядчика.')}</p><ul>${(p.pains||[]).slice(0,7).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;
ensureStrategyBlocks(p);
const accents=activeStrategyBlocks(p,'utps').slice(0,8).map(b=>b.text?`${b.title}: ${b.text}`:b.title);
const hyps=activeStrategyBlocks(p,'hypotheses').slice(0,8).map(b=>({name:b.title,text:b.text}));
const planList=(p.tasks||[]).slice(0,14).map(t=>({stage:t.stage||'Этап',text:`${t.task}${t.owner?` — ${t.owner}`:''}`}));
const kpiText=`При бюджете ${fmt(p.kpi?.weeklyBudget)} ₽ в неделю и цели ${fmt(p.kpi?.desiredOrdersWeek)} заказов, при конверсии лид → продажа ${pct(p.kpi?.leadToSale)}, системе нужно получать примерно ${fmt(kpi.needLeads)} лидов в неделю. Ориентир по CPL для выполнения цели — около ${fmt(kpi.possibleCpl)} ₽. Если фактический CPL будет выше, нужно либо повышать конверсию отдела продаж, либо пересматривать бюджет и цель.`;
document.getElementById('view-report').innerHTML=`
<div class="actions no-print" style="justify-content:center;margin-bottom:16px"><button class="btn" onclick="window.print()">Печать / PDF</button><button class="btn" onclick="copyText(document.querySelector('.report').innerText)">Скопировать отчет</button></div><article class="report"><div class="report-cover"><div><h1>Стратегия запуска рекламного проекта</h1><p class="muted">Agency Brief Systems · ${esc(today())} · алгоритмический отчет</p><h2 style="border:0;padding:0;margin-top:22px">${esc(p.title)}</h2><p><b>Ниша:</b> ${esc(p.niche||'не указана')}<br><b>Статус:</b> ${esc(p.status||'Бриф')}</p></div><div class="report-logo">ABS</div></div><h2>1. Краткий вывод</h2><div id="reportSummary">${summaryHtml}</div><h2>2. Приоритетные направления</h2><div id="reportPriorities"><div class="table-wrap"><table><thead><tr><th>Услуга</th><th>Спрос</th><th>Предложение</th><th>Приоритет</th><th>Вывод</th></tr></thead><tbody>${best.slice(0,8).map(s=>`<tr><td><b>${esc(s.name)}</b></td><td>${fmt(s.demand)}</td><td>${fmt(s.supply)}</td><td>${s.score}/100</td><td>${serviceDecision(s.score)}</td></tr>`).join('')}</tbody></table></div></div><h2>3. Аудитория и психология</h2><div id="reportAudience">${audienceHtml}</div><h2>4. Рекламные акценты</h2><ul id="reportAccents">${accents.map(x=>`<li>${esc(x)}</li>`).join('')}</ul><h2>5. Гипотезы для теста</h2><ul id="reportHypotheses">${hyps.map(x=>`<li><b>${esc(x.name||'Гипотеза')}:</b> ${esc(x.text||'')}</li>`).join('')}</ul><h2>6. KPI и экономика</h2><div id="reportKpi">${textToParagraphs(kpiText)}</div><h2>7. Риски перед запуском</h2><ul id="reportRisks">${risks.map(r=>`<li><b>${esc(r.title||'Риск')}:</b> ${esc(r.text||'')}</li>`).join('')||'<li>Критичных рисков не найдено.</li>'}</ul><h2>8. Что уточнить у клиента</h2><ul id="reportQuestions">${qs.map(q=>`<li><b>${esc(q.t||'Вопрос')}</b> ${esc(q.why||'')}</li>`).join('')||'<li>Ключевые вопросы закрыты.</li>'}</ul><h2>9. План запуска</h2><ul id="reportPlan">${planList.map(t=>`<li><b>${esc(t.stage||'Этап')}:</b> ${esc(t.text||'')}</li>`).join('')||'<li>План запуска будет сформирован после импорта чек-листа.</li>'}</ul></article>`;
}

function textToParagraphs(text){
const parts=String(text||'').split(/\n\s*\n/).map(x=>x.trim()).filter(Boolean);
return parts.map(x=>`<p>${esc(x).replace(/\n/g,'<br>')}</p>`).join('')||'<p></p>';
}
