function setUiSetting(k,v){state.settings.ui=state.settings.ui||{};state.settings.ui[k]=v;saveState();renderAll();}
function renderSettings(){
const theme=state.settings?.theme||'hybrid'; const w=getWeights(); const ui=state.settings.ui||{showProjectIds:true,confirmDelete:true};
document.getElementById('view-settings').innerHTML=`
<div class="grid cols-2"><div class="card"><h2>Тема сайта</h2><div class="theme-picker"><div class="theme-card ${theme==='white'?'active':''}" onclick="setSiteTheme('white')"><div class="theme-preview light"><span></span><span></span></div><b>Белая</b><div class="small muted">светлый интерфейс</div></div><div class="theme-card ${theme==='black'?'active':''}" onclick="setSiteTheme('black')"><div class="theme-preview dark"><span></span><span></span></div><b>Черная</b><div class="small muted">темный интерфейс</div></div><div class="theme-card ${theme==='hybrid'?'active':''}" onclick="setSiteTheme('hybrid')"><div class="theme-preview"><span></span><span></span></div><b>Бело-черная</b><div class="small muted">темное меню + светлая работа</div></div></div></div><div class="card"><h2>Настройки алгоритмов</h2><div class="grid cols-2"><div class="field"><label>Вес спроса</label><input value="${esc(w.demand)}" oninput="setWeight('demand',this.value)"></div><div class="field"><label>Вес баланса спрос/предложение</label><input value="${esc(w.balance)}" oninput="setWeight('balance',this.value)"></div><div class="field"><label>Вес экономики</label><input value="${esc(w.economics)}" oninput="setWeight('economics',this.value)"></div><div class="field"><label>Вес приоритета клиента</label><input value="${esc(w.client)}" oninput="setWeight('client',this.value)"></div><div class="field"><label>Вес материалов</label><input value="${esc(w.materials)}" oninput="setWeight('materials',this.value)"></div></div><button class="btn" onclick="resetWeights()">Сбросить веса</button></div></div><div class="card" style="margin-top:16px"><h2>Параметры интерфейса</h2><div class="settings-grid"><div class="toggle-row"><div><b>Показывать ID проекта</b><div class="small muted">в таблице проектов</div></div><label class="switch"><input type="checkbox" ${ui.showProjectIds!==false?'checked':''} onchange="setUiSetting('showProjectIds',this.checked)"><span></span></label></div><div class="toggle-row"><div><b>Подтверждать удаление</b><div class="small muted">для проектов и файлов</div></div><label class="switch"><input type="checkbox" ${ui.confirmDelete!==false?'checked':''} onchange="setUiSetting('confirmDelete',this.checked)"><span></span></label></div><div class="toggle-row"><div><b>Автопереход в карточку проекта</b><div class="small muted">после создания проекта</div></div><label class="switch"><input type="checkbox" checked disabled><span></span></label></div></div></div>`;
}

function setKpi(k,v){const p=currentProject();p.kpi=p.kpi||{};p.kpi[k]=number(v);p.updatedAt=today();saveState();}
function setMaterial(k,v){const p=currentProject();p.materials=p.materials||{};p.materials[k]=v;p.updatedAt=today();saveState();}
